{
  "Header": {
    "Original": "CVE-2024-24680 (An issue was discovered in Django 3.2 before 3.2.24, 4.2 before 4.2.10 ...)",
    "ID": "CVE-2024-24680",
    "Description": "(An issue was discovered in Django 3.2 before 3.2.24, 4.2 before 4.2.10 ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-4210-1}",
      "Type": "xref",
      "Bugs": [
        "DLA-4210-1"
      ]
    },
    {
      "Original": "- python-django 3:4.2.10-1",
      "Type": "package",
      "Package": "python-django",
      "Kind": "fixed",
      "Version": "3:4.2.10-1"
    },
    {
      "Original": "[bookworm] - python-django \u003cpostponed\u003e (Minor issue, fix along in future update)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "python-django",
      "Kind": "postponed",
      "Description": "Minor issue, fix along in future update"
    },
    {
      "Original": "[buster] - python-django \u003cpostponed\u003e (Minor issue, fix along in future update)",
      "Type": "package",
      "Release": "buster",
      "Package": "python-django",
      "Kind": "postponed",
      "Description": "Minor issue, fix along in future update"
    },
    {
      "Original": "NOTE: https://www.openwall.com/lists/oss-security/2024/02/06/2",
      "Type": "NOTE",
      "Description": "https://www.openwall.com/lists/oss-security/2024/02/06/2"
    },
    {
      "Original": "NOTE: https://www.djangoproject.com/weblog/2024/feb/06/security-releases/",
      "Type": "NOTE",
      "Description": "https://www.djangoproject.com/weblog/2024/feb/06/security-releases/"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/django/django/commit/55519d6cf8998fe4c8f5c8abffc2b10a7c3d14e9 (main)",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/django/django/commit/55519d6cf8998fe4c8f5c8abffc2b10a7c3d14e9 (main)"
    },
    {
      "Original": "NOTE: Regression fix: https://github.com/django/django/commit/2f14c2cedc9c92373471c1f98a80c81ba299584a (main)",
      "Type": "NOTE",
      "Description": "Regression fix: https://github.com/django/django/commit/2f14c2cedc9c92373471c1f98a80c81ba299584a (main)"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/django/django/commit/16a8fe18a3b81250f4fa57e3f93f0599dc4895bc (5.0.2)",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/django/django/commit/16a8fe18a3b81250f4fa57e3f93f0599dc4895bc (5.0.2)"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/django/django/commit/572ea07e84b38ea8de0551f4b4eda685d91d09d2 (4.2.10)",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/django/django/commit/572ea07e84b38ea8de0551f4b4eda685d91d09d2 (4.2.10)"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/django/django/commit/c1171ffbd570db90ca206c30f8e2b9f691243820 (3.2.24)",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/django/django/commit/c1171ffbd570db90ca206c30f8e2b9f691243820 (3.2.24)"
    }
  ]
}